---

- name: GET Nagios
  get_url: url={{ nagiosurl }} dest={{ download_dir }}/{{ nagiossrc }}.tar.gz

- name: Unpack Nagios source files
  shell: cd {{ ansible_env.HOME }}/nagios && tar -xzvf {{ nagiossrc }}.tar.gz creates={{ ansible_env['HOME'] }}/nagios/{{ nagiossrc }}

- name: Configure
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && ./configure --with-command-group={{ monitoring_command_group }} creates={{ ansible_env['HOME'] }}/nagios/{{ nagiossrc }}/Makefile
  when: ansible_distribution == 'CentOS'

- name: Configure
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && ./configure --with-command-group={{ monitoring_command_group }} creates={{ ansible_env['HOME'] }}/nagios/{{ nagiossrc }}/Makefile
  when: ansible_distribution == 'Debian'

- name: Configure for Ubuntu 12.04
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && ./configure --with-command-group={{ monitoring_command_group }} creates={{ ansible_env['HOME'] }}/nagios/{{ nagiossrc }}/Makefile
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '12.04'

- name: Configure for Ubuntu 14.04
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && ./configure --with-command-group={{ monitoring_command_group }} -with-httpd_conf=/etc/apache2/conf-available creates={{ ansible_env['HOME'] }}/nagios/{{ nagiossrc }}/Makefile
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Make all
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make all creates={{ ansible_env['HOME'] }}/nagios/{{ nagiossrc }}/base/nagios

- name: Make install
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install creates=/usr/local/nagios/bin/nagios

- name: Make install-config
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-config creates=/usr/local/nagios/etc/nagios.cfg

- name: Make install-commandmode
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-commandmode creates=/usr/local/nagios/var/rw

- name: Make install-devel
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-devel creates=/usr/local/nagios/include/nagios/nagios.h

- name: Make install-webconf
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-webconf creates=/etc/httpd/conf.d/nagios.conf
  notify: restart apache
  when: ansible_distribution == 'CentOS'

- name: Make install-webconf
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-webconf creates=/etc/apache2/conf.d/nagios.conf
  notify: restart apache
  when: ansible_distribution == 'Debian'

- name: Make install-webconf Ubuntu 12.04
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-webconf creates=/etc/apache2/conf.d/nagios.conf
  notify: restart apache
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '12.04'

- name: Make install-webconf Ubuntu 14.04
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-webconf creates=/etc/apache2/conf-available/nagios.conf
  notify: restart apache
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Make install-init
  shell: cd {{ ansible_env.HOME }}/nagios/{{ nagiossrc }} && make install-init creates=/etc/init.d/nagios

- name: Set htpasswd for nagiosadmin
  htpasswd: path=/usr/local/nagios/etc/htpasswd.users name={{ item.user }} password={{ item.pass }} state=present
  with_items: "{{ nagios_users }}"

- name: Ensure Nagios is started
  service: name=nagios state=started enabled=yes
