---

- name: Downloading the EPEL repository definitions.
  get_url: url=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm dest={{ ansible_env.HOME }}/nagios/epel-release-6-8.noarch.rpm
  when: is_centos

- name: Downloading and enable the EPEL repository definitions.
  yum: name={{ ansible_env.HOME }}/nagios//epel-release-6-8.noarch.rpm state=present
  when: is_centos

- name: install apache
  yum: pkg={{ item }} state=present
  with_items:
   - php
   - httpd
   - libsemanage-python
   - libselinux-python

- name: Install Nagios prerequisites for CentOS
  yum: pkg={{ item }} state=present
  with_items:
   - gcc
   - glibc
   - glibc-common
   - gd
   - gd-devel
   - make
   - perl
   - perl-devel
   - wget
   - python-passlib

- name: Install plugin prerequisites for CentOS
  yum: pkg={{ item }} state=present
  with_items:
   - openssl-devel
   - fping
   - openldap-devel
   - postgresql-devel
   - radiusclient-ng-devel
   - samba-client
   - libsmbclient
